backend: "ascendcl"
max_batch_size: 4
dynamic_batching {
    preferred_batch_size: [ 1, 2, 4 ]
}

input [
    {
        name: "input"
        data_type: TYPE_FP32
        dims: [ 3, 640, 640 ]
    }
]
output [
    {
        name: "output"
        data_type: TYPE_FP32
        dims: [ 25200, 85 ]
    }
]

instance_group [
    {
        count: 1
        kind: KIND_MODEL
    }
]