backend: "dlnne"
max_batch_size: 16

input [
    {
        name: "input_ids"
        data_type: TYPE_INT64
        dims: [ 32 ]
    },
    {
        name: "attention_mask"
        data_type: TYPE_INT64
        dims: [ 32 ]
    },
    {
        name: "token_type_ids"
        data_type: TYPE_INT64
        dims: [ 32 ]
    }
]
output [
    {
        name: "output"
        data_type: TYPE_FP32
        dims: [ 32, 28996 ]
    }
]

instance_group [
    {
        count: 1
        kind: KIND_MODEL
    }
]