backend: "python"
max_batch_size: 16
dynamic_batching {
    preferred_batch_size: [ 1, 2, 4, 8, 16 ]
}

input [
    {
        name: "input"
        data_type: TYPE_FP32
        dims: [ 3, 224, 224 ]
    }
]
output [
    {
        name: "output"
        data_type: TYPE_FP32
        dims: [ 1000 ]
    }
]

instance_group [
    {
        count: 2
        kind: KIND_MODEL
    }
]